Add pop-up to portfolio
Luchy-B/Portfolio pull request #12
Opened 2023-02-03 15:45 UTC by Luchy-B

- Add pop-up design to portfolio
- Add Functionality using JS to pop-up

2023-02-03 20:55 UTC, huseyinbiyik requested changes
Hi team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Projects and popups created dynamically 👌
- Linter set up well and checks pass 🟢
- Github flow followed 👌

## Required Changes ♻️
- You did a great job in general. But let's fix this bug occurs on mobile version. When you open the mobile version, a broken popup and nav opens automatically. Kindly fix that 🦾
![Screen Recording 2023-02-03 at 11 25 06 PM](https://user-images.githubusercontent.com/25887253/216708967-e076d44b-cd81-44f5-83cd-0d4b64b1cb37.gif)

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-03 20:55 UTC, huseyinbiyik commented on styles.css
>  .btn-1 {
Great job, the buttons are working correctly 👌 But let's add some space to the bottom of the button. 
<img width="609" alt="Screenshot 2023-02-03 at 11 27 52 PM" src="https://user-images.githubusercontent.com/25887253/216704786-e4467b9e-045b-441c-ba2f-52435bdf1872.png">
<img width="609" alt="Screenshot 2023-02-03 at 11 28 12 PM" src="https://user-images.githubusercontent.com/25887253/216704791-070164c6-d6d7-4c33-88ba-99678f2d072f.png">

2023-02-03 20:55 UTC, huseyinbiyik commented on index.html
> +         <hr>
Please change the color of the hr element to match the figma design 👨‍🎨
<img width="798" alt="Screenshot 2023-02-03 at 11 26 04 PM" src="https://user-images.githubusercontent.com/25887253/216705875-fe0ff961-a82e-4144-ab91-25524e3f5623.png">

2023-02-03 20:55 UTC, huseyinbiyik commented on index.html
> +            <!-- <li class="canopyLi1">CANOPY</li>
Kindly don't leave any uncommented code in your codebase. In this way, you can keep your codebase clean, organized and professional 👍 If you need these codes later you can travel through your history with git. 📝 Please don't forget to remove the uncommented code in index.html as well 👍

2023-02-03 20:55 UTC, huseyinbiyik commented on styles.css
> +/* Modal Design */
-Excellent job with the backdrop blur 👨‍🎨 But let's fix left and right padding of the image like on the template.
- Please make sure you don't stretch the image, it is a very bad practice for the images. What you can do is, you can have a vertical overflow and user can go down to read the bottom section of the modal.

<img width="1407" alt="Screenshot 2023-02-03 at 11 21 53 PM" src="https://user-images.githubusercontent.com/25887253/216707451-67eabe02-64d4-452b-9a4f-31e00d2f9e58.png">
<img width="1407" alt="Screenshot 2023-02-03 at 11 22 28 PM" src="https://user-images.githubusercontent.com/25887253/216707459-7a751401-6ae9-4159-952a-bac69f9618ed.png">

2023-02-03 20:55 UTC, huseyinbiyik commented on styles.css
> +hr {
Good job adding separator on mobile version. 👍 But let's add separator also for the desktop version like on the Figma template.
<img width="546" alt="Screenshot 2023-02-03 at 11 19 57 PM" src="https://user-images.githubusercontent.com/25887253/216707780-c3daffbc-ab93-45ac-a327-a0c812278fbe.png">

2023-02-03 20:55 UTC, huseyinbiyik commented on styles.css
> +.modal-button {
Kindly make sure your button matches with Figma design. Here, buttons have different sizes, icon and text is not aligned well and not enough between text and icon.👍
<img width="802" alt="Screenshot 2023-02-03 at 11 20 41 PM" src="https://user-images.githubusercontent.com/25887253/216707854-f8c08d57-ac3a-4b2d-8330-c84ad1eee4c3.png">
<img width="717" alt="Screenshot 2023-02-03 at 11 21 10 PM" src="https://user-images.githubusercontent.com/25887253/216707857-7c6a20c7-9a8e-4d3d-b623-cf471ffcd631.png">

2023-02-04 02:01 UTC, Shedrack-Sunday requested changes
Hi @Luchy-B       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Descriptive commit messages 
  
Required Changes ♻️

- [x] You did make efforts in the  Project and you really need a great job. However, there seem to be a few adjustments needed on the mobile view pop-up to make your whole code stand out and look good. 👍 

- [x] The Reason for taking web accessibility seriously onscreen sizes is because it ensures that users with varying devices, including smaller screens such as smartphones, are able to access and use a website effectively. This includes individuals with disabilities who may use assistive technologies such as screen readers or magnifiers to access the web. By ensuring that websites are accessible on smaller viewports, developers can help make the web more inclusive for all users.  Kindly fix the margin on the right of the screen view. good job so far 👏 


_check the comment section for a detailed review_

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application.


Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.


Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-04 02:01 UTC, Shedrack-Sunday commented on index.html
> +          </ul>
- [ ]  Also as suggested by the previous reviewer and rightly so, I noticed you did make changes, but the buttons for your live and source links should display on the first render. presently, the pop-up renders but without the button on the screen on the mobile view. This is in line with best practices for web accessibility and gives the best user experience 👏

- Make sure the other space changes recommended by the previous reviewer are taken note of when you fix the buttons.

# Your view

![image](https://user-images.githubusercontent.com/50990925/216740377-0b274469-259b-4f5e-b3cd-c95a3e6a9529.png)

# Expected figma render:
![image](https://user-images.githubusercontent.com/50990925/216740489-ccedae38-3efa-4d61-88bb-d15b5f9f5f72.png)

2023-02-04 16:24 UTC, didierganthier requested changes
Hi Team 👥 ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-02-04 16:24 UTC, didierganthier commented on styles.css
> +}
Great job 🎉 addressing some of the changes requested by the previous reviewers. You're almost there 😉 but I noticed that while implementing the changes certain things got introduced. Your popup works and looks very well on mobile but the `border-radius` on the right side isn't quite there for the Desktop. See below 👇🏽 

![Screenshot 2023-02-04 at 11 21 18](https://user-images.githubusercontent.com/45739963/216778202-b0ee3d77-c8e4-49d0-9eae-f28f3ef075fa.png)

2023-02-04 22:45 UTC, huseyinbiyik approved these changes
Hi team,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- Commit messages are meaningful and written in imperative tense 📝
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions
- You can move your license text to a license file instead of keeping it on your README directly.
<img width="818" alt="Screenshot 2023-02-05 at 1 43 14 AM" src="https://user-images.githubusercontent.com/25887253/216792631-b28cfbd9-2607-4e38-9413-255ffd9e7c48.png">

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-04 22:58 UTC, merged