Contact me section
Luchy-B/Portfolio pull request #3
Opened 2023-01-18 14:27 UTC by Luchy-B

Add contact me form to portfolio
Add validations to form

2023-01-18 14:35 UTC, BregornOriginal requested changes
Hi @Team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

🔴 🔴  ***You have submitted a project, that is not passing Linters check*** 🔴 🔴 🔴 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-18 18:27 UTC, huseyinbiyik requested changes
Hi team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Collaborative work 🧠🧠
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 18:27 UTC, huseyinbiyik commented on index.html
> +  <section class="contact-Form">
Kindly stick to the design and fix the gray area like on the Figma template. 👨‍🎨
<img width="462" alt="Screenshot 2023-01-18 at 9 10 15 PM" src="https://user-images.githubusercontent.com/25887253/213261405-9eaf351f-26ee-46b1-8df0-34c9edbb7b17.png">
<img width="462" alt="Screenshot 2023-01-18 at 9 10 44 PM" src="https://user-images.githubusercontent.com/25887253/213261409-f3c242a6-663a-4122-9252-5440b7c360a4.png">

2023-01-18 18:27 UTC, huseyinbiyik commented on index.html
> +            <p>
Please follow the Figma template and fix the padding left and right side of the paragraph. It needs to be 24px as you can see below.
<img width="953" alt="Screenshot 2023-01-18 at 9 04 09 PM" src="https://user-images.githubusercontent.com/25887253/213262200-636ff095-8a9b-4c02-96ab-1dab50857a47.png">
<img width="601" alt="Screenshot 2023-01-18 at 9 05 17 PM" src="https://user-images.githubusercontent.com/25887253/213262209-438aafbe-3ba5-4e1f-87b2-e1f14b7f7a42.png">

2023-01-18 18:27 UTC, huseyinbiyik commented on index.html
> +                with it
Please stick to the Figma template and fix the alignment of the paragraph text with `text-align:center` and font-size and font-weight. 
<img width="910" alt="Screenshot 2023-01-18 at 9 06 16 PM" src="https://user-images.githubusercontent.com/25887253/213262596-970c3453-2efe-463c-a9a2-f7ccc67ec28d.png">

2023-01-18 18:27 UTC, huseyinbiyik commented on index.html
> +            <img src="images/end-Line.png" alt="Black-Line" class="end-Line">
Form submission works properly but let's make the design flawless. Here, there is an alignment issue. You need 24px padding from left and right for name, email, text area, and button. So they will be aligned.
<img width="386" alt="Screenshot 2023-01-18 at 9 08 24 PM" src="https://user-images.githubusercontent.com/25887253/213263070-8932f202-579a-4d62-ac82-cb5af91a1e6a.png">

2023-01-18 18:27 UTC, huseyinbiyik commented on index.html
> +                <button type="submit" class="button">Get in touch</button>
Kindly add active and pressed states for your submit button as requested on the project requirement. Please check the related area on the Figma as guide.
<img width="462" alt="Screenshot 2023-01-18 at 9 11 37 PM" src="https://user-images.githubusercontent.com/25887253/213263531-f2a8f0f1-8d91-4850-bf13-31f1c4baf14a.png">

2023-01-19 10:23 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Luchy-B, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Collaborative work 🧠🧠
 - Linter set up well and checks pass 🟢
 - Github flow followed 👌
 - .gitignore used to ignore requested files 📁
 - Commit messages are meaningful and written in imperative tense 📝
 - PR description is descriptive 📝

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 10:23 UTC, leonardodiasb commented on index.html
> +                        <textarea id="message" cols="40" rows="10" required maxlength="500" minlength="10" name="message"placeholder="Write your message here"></textarea>
- [ ] You did a great job fixing the issues the previous code reviewer mentioned. But the `textarea` of your contact form is still larger. I would recommend you remove the `cols` and `rows` attributes and use `width` and `height` to style it on your CSS file. Kindly fix it so the `textarea` is aligned with the rest of the inputs.

2023-01-19 11:24 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @Luchy-B  👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️professional PR👍 
✔️professional README👍 
✔️No linter Errors 👍 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 12:46 UTC, merged